
-- Enable RLS on all remaining tables
ALTER TABLE public.artist_portfolio_assets ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.artist_style_models ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.image_embeddings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.originality_checks ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.sleeve_canvases ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.layout_jobs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.sleeve_concepts ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.concept_jobs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.concept_variants ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.conversion_bandit_state ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.final_sketches ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.ar_packs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.ar_live_sessions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.ar_live_records ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.ar_live_calibrations ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.ar_live_renders ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.relight_profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.ar_shader_presets ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.job_traces ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.job_errors ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.codesign_sessions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.codesign_events ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.preference_model_state ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.codesign_variants ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.conversion_events ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.conversion_state ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.copy_variants ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.offer_strategies ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.provider_health ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.provider_routes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.chaos_rules ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.quantum_runs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.ensemble_runs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.ensemble_candidates ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.eval_suites ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.eval_results ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.feasibility_runs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.offline_queues ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.device_caps ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.collab_rooms ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.collab_ops ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.design_versions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.design_comments ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.training_examples ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.prompt_versions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.model_registry ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.ab_rollouts ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.originality_reports ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.provenance_chain ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.style_tokens ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.style_token_sets ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.style_token_events ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.body_profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.body_landmarks ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.body_uv_maps ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.deformation_zones ENABLE ROW LEVEL SECURITY;

-- Service role policies for all tables (edge functions need access)
CREATE POLICY "Service role access artist_portfolio_assets" ON public.artist_portfolio_assets FOR ALL USING (auth.role() = 'service_role');
CREATE POLICY "Service role access artist_style_models" ON public.artist_style_models FOR ALL USING (auth.role() = 'service_role');
CREATE POLICY "Service role access image_embeddings" ON public.image_embeddings FOR ALL USING (auth.role() = 'service_role');
CREATE POLICY "Service role access originality_checks" ON public.originality_checks FOR ALL USING (auth.role() = 'service_role');
CREATE POLICY "Service role access sleeve_canvases" ON public.sleeve_canvases FOR ALL USING (auth.role() = 'service_role');
CREATE POLICY "Service role access layout_jobs" ON public.layout_jobs FOR ALL USING (auth.role() = 'service_role');
CREATE POLICY "Service role access sleeve_concepts" ON public.sleeve_concepts FOR ALL USING (auth.role() = 'service_role');
CREATE POLICY "Service role access concept_jobs" ON public.concept_jobs FOR ALL USING (auth.role() = 'service_role');
CREATE POLICY "Service role access concept_variants" ON public.concept_variants FOR ALL USING (auth.role() = 'service_role');
CREATE POLICY "Service role access conversion_bandit_state" ON public.conversion_bandit_state FOR ALL USING (auth.role() = 'service_role');
CREATE POLICY "Service role access final_sketches" ON public.final_sketches FOR ALL USING (auth.role() = 'service_role');
CREATE POLICY "Service role access ar_packs" ON public.ar_packs FOR ALL USING (auth.role() = 'service_role');
CREATE POLICY "Service role access ar_live_sessions" ON public.ar_live_sessions FOR ALL USING (auth.role() = 'service_role');
CREATE POLICY "Service role access ar_live_records" ON public.ar_live_records FOR ALL USING (auth.role() = 'service_role');
CREATE POLICY "Service role access ar_live_calibrations" ON public.ar_live_calibrations FOR ALL USING (auth.role() = 'service_role');
CREATE POLICY "Service role access ar_live_renders" ON public.ar_live_renders FOR ALL USING (auth.role() = 'service_role');
CREATE POLICY "Service role access relight_profiles" ON public.relight_profiles FOR ALL USING (auth.role() = 'service_role');
CREATE POLICY "Service role access ar_shader_presets" ON public.ar_shader_presets FOR ALL USING (auth.role() = 'service_role');
CREATE POLICY "Service role access job_traces" ON public.job_traces FOR ALL USING (auth.role() = 'service_role');
CREATE POLICY "Service role access job_errors" ON public.job_errors FOR ALL USING (auth.role() = 'service_role');
CREATE POLICY "Service role access codesign_sessions" ON public.codesign_sessions FOR ALL USING (auth.role() = 'service_role');
CREATE POLICY "Service role access codesign_events" ON public.codesign_events FOR ALL USING (auth.role() = 'service_role');
CREATE POLICY "Service role access preference_model_state" ON public.preference_model_state FOR ALL USING (auth.role() = 'service_role');
CREATE POLICY "Service role access codesign_variants" ON public.codesign_variants FOR ALL USING (auth.role() = 'service_role');
CREATE POLICY "Service role access conversion_events" ON public.conversion_events FOR ALL USING (auth.role() = 'service_role');
CREATE POLICY "Service role access conversion_state" ON public.conversion_state FOR ALL USING (auth.role() = 'service_role');
CREATE POLICY "Service role access copy_variants" ON public.copy_variants FOR ALL USING (auth.role() = 'service_role');
CREATE POLICY "Service role access offer_strategies" ON public.offer_strategies FOR ALL USING (auth.role() = 'service_role');
CREATE POLICY "Service role access provider_health" ON public.provider_health FOR ALL USING (auth.role() = 'service_role');
CREATE POLICY "Service role access provider_routes" ON public.provider_routes FOR ALL USING (auth.role() = 'service_role');
CREATE POLICY "Service role access chaos_rules" ON public.chaos_rules FOR ALL USING (auth.role() = 'service_role');
CREATE POLICY "Service role access quantum_runs" ON public.quantum_runs FOR ALL USING (auth.role() = 'service_role');
CREATE POLICY "Service role access ensemble_runs" ON public.ensemble_runs FOR ALL USING (auth.role() = 'service_role');
CREATE POLICY "Service role access ensemble_candidates" ON public.ensemble_candidates FOR ALL USING (auth.role() = 'service_role');
CREATE POLICY "Service role access eval_suites" ON public.eval_suites FOR ALL USING (auth.role() = 'service_role');
CREATE POLICY "Service role access eval_results" ON public.eval_results FOR ALL USING (auth.role() = 'service_role');
CREATE POLICY "Service role access feasibility_runs" ON public.feasibility_runs FOR ALL USING (auth.role() = 'service_role');
CREATE POLICY "Service role access offline_queues" ON public.offline_queues FOR ALL USING (auth.role() = 'service_role');
CREATE POLICY "Service role access device_caps" ON public.device_caps FOR ALL USING (auth.role() = 'service_role');
CREATE POLICY "Service role access collab_rooms" ON public.collab_rooms FOR ALL USING (auth.role() = 'service_role');
CREATE POLICY "Service role access collab_ops" ON public.collab_ops FOR ALL USING (auth.role() = 'service_role');
CREATE POLICY "Service role access design_versions" ON public.design_versions FOR ALL USING (auth.role() = 'service_role');
CREATE POLICY "Service role access design_comments" ON public.design_comments FOR ALL USING (auth.role() = 'service_role');
CREATE POLICY "Service role access training_examples" ON public.training_examples FOR ALL USING (auth.role() = 'service_role');
CREATE POLICY "Service role access prompt_versions" ON public.prompt_versions FOR ALL USING (auth.role() = 'service_role');
CREATE POLICY "Service role access model_registry" ON public.model_registry FOR ALL USING (auth.role() = 'service_role');
CREATE POLICY "Service role access ab_rollouts" ON public.ab_rollouts FOR ALL USING (auth.role() = 'service_role');
CREATE POLICY "Service role access originality_reports" ON public.originality_reports FOR ALL USING (auth.role() = 'service_role');
CREATE POLICY "Service role access provenance_chain" ON public.provenance_chain FOR ALL USING (auth.role() = 'service_role');
CREATE POLICY "Service role access style_tokens" ON public.style_tokens FOR ALL USING (auth.role() = 'service_role');
CREATE POLICY "Service role access style_token_sets" ON public.style_token_sets FOR ALL USING (auth.role() = 'service_role');
CREATE POLICY "Service role access style_token_events" ON public.style_token_events FOR ALL USING (auth.role() = 'service_role');
CREATE POLICY "Service role access body_profiles" ON public.body_profiles FOR ALL USING (auth.role() = 'service_role');
CREATE POLICY "Service role access body_landmarks" ON public.body_landmarks FOR ALL USING (auth.role() = 'service_role');
CREATE POLICY "Service role access body_uv_maps" ON public.body_uv_maps FOR ALL USING (auth.role() = 'service_role');
CREATE POLICY "Service role access deformation_zones" ON public.deformation_zones FOR ALL USING (auth.role() = 'service_role');
CREATE POLICY "Service role access vision_extractions" ON public.vision_extractions FOR ALL USING (auth.role() = 'service_role');
CREATE POLICY "Service role access vision_3d_jobs" ON public.vision_3d_jobs FOR ALL USING (auth.role() = 'service_role');
CREATE POLICY "Service role access ai_runs" ON public.ai_runs FOR ALL USING (auth.role() = 'service_role');
CREATE POLICY "Service role access usage_events" ON public.usage_events FOR ALL USING (auth.role() = 'service_role');
CREATE POLICY "Service role access vision_assets" ON public.vision_assets FOR ALL USING (auth.role() = 'service_role');
CREATE POLICY "Service role access feature_flags" ON public.feature_flags FOR ALL USING (auth.role() = 'service_role');
CREATE POLICY "Service role access concierge_offer_policy" ON public.concierge_offer_policy FOR ALL USING (auth.role() = 'service_role');
CREATE POLICY "Service role access concierge_actions_log" ON public.concierge_actions_log FOR ALL USING (auth.role() = 'service_role');
